# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/e/work/shenda_code/BF/mic_array

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/e/work/shenda_code/BF/mic_array

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/work/shenda_code/BF/mic_array/CMakeFiles /mnt/e/work/shenda_code/BF/mic_array/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/work/shenda_code/BF/mic_array/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mic_array

# Build rule for target.
mic_array: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mic_array
.PHONY : mic_array

# fast build rule for target.
mic_array/fast:
	$(MAKE) -f CMakeFiles/mic_array.dir/build.make CMakeFiles/mic_array.dir/build
.PHONY : mic_array/fast

src/hq_malloc.o: src/hq_malloc.c.o

.PHONY : src/hq_malloc.o

# target to build an object file
src/hq_malloc.c.o:
	$(MAKE) -f CMakeFiles/mic_array.dir/build.make CMakeFiles/mic_array.dir/src/hq_malloc.c.o
.PHONY : src/hq_malloc.c.o

src/hq_malloc.i: src/hq_malloc.c.i

.PHONY : src/hq_malloc.i

# target to preprocess a source file
src/hq_malloc.c.i:
	$(MAKE) -f CMakeFiles/mic_array.dir/build.make CMakeFiles/mic_array.dir/src/hq_malloc.c.i
.PHONY : src/hq_malloc.c.i

src/hq_malloc.s: src/hq_malloc.c.s

.PHONY : src/hq_malloc.s

# target to generate assembly for a file
src/hq_malloc.c.s:
	$(MAKE) -f CMakeFiles/mic_array.dir/build.make CMakeFiles/mic_array.dir/src/hq_malloc.c.s
.PHONY : src/hq_malloc.c.s

src/hq_tx_2mic_ns.o: src/hq_tx_2mic_ns.c.o

.PHONY : src/hq_tx_2mic_ns.o

# target to build an object file
src/hq_tx_2mic_ns.c.o:
	$(MAKE) -f CMakeFiles/mic_array.dir/build.make CMakeFiles/mic_array.dir/src/hq_tx_2mic_ns.c.o
.PHONY : src/hq_tx_2mic_ns.c.o

src/hq_tx_2mic_ns.i: src/hq_tx_2mic_ns.c.i

.PHONY : src/hq_tx_2mic_ns.i

# target to preprocess a source file
src/hq_tx_2mic_ns.c.i:
	$(MAKE) -f CMakeFiles/mic_array.dir/build.make CMakeFiles/mic_array.dir/src/hq_tx_2mic_ns.c.i
.PHONY : src/hq_tx_2mic_ns.c.i

src/hq_tx_2mic_ns.s: src/hq_tx_2mic_ns.c.s

.PHONY : src/hq_tx_2mic_ns.s

# target to generate assembly for a file
src/hq_tx_2mic_ns.c.s:
	$(MAKE) -f CMakeFiles/mic_array.dir/build.make CMakeFiles/mic_array.dir/src/hq_tx_2mic_ns.c.s
.PHONY : src/hq_tx_2mic_ns.c.s

src/kiss_fft.o: src/kiss_fft.c.o

.PHONY : src/kiss_fft.o

# target to build an object file
src/kiss_fft.c.o:
	$(MAKE) -f CMakeFiles/mic_array.dir/build.make CMakeFiles/mic_array.dir/src/kiss_fft.c.o
.PHONY : src/kiss_fft.c.o

src/kiss_fft.i: src/kiss_fft.c.i

.PHONY : src/kiss_fft.i

# target to preprocess a source file
src/kiss_fft.c.i:
	$(MAKE) -f CMakeFiles/mic_array.dir/build.make CMakeFiles/mic_array.dir/src/kiss_fft.c.i
.PHONY : src/kiss_fft.c.i

src/kiss_fft.s: src/kiss_fft.c.s

.PHONY : src/kiss_fft.s

# target to generate assembly for a file
src/kiss_fft.c.s:
	$(MAKE) -f CMakeFiles/mic_array.dir/build.make CMakeFiles/mic_array.dir/src/kiss_fft.c.s
.PHONY : src/kiss_fft.c.s

src/kiss_fftr.o: src/kiss_fftr.c.o

.PHONY : src/kiss_fftr.o

# target to build an object file
src/kiss_fftr.c.o:
	$(MAKE) -f CMakeFiles/mic_array.dir/build.make CMakeFiles/mic_array.dir/src/kiss_fftr.c.o
.PHONY : src/kiss_fftr.c.o

src/kiss_fftr.i: src/kiss_fftr.c.i

.PHONY : src/kiss_fftr.i

# target to preprocess a source file
src/kiss_fftr.c.i:
	$(MAKE) -f CMakeFiles/mic_array.dir/build.make CMakeFiles/mic_array.dir/src/kiss_fftr.c.i
.PHONY : src/kiss_fftr.c.i

src/kiss_fftr.s: src/kiss_fftr.c.s

.PHONY : src/kiss_fftr.s

# target to generate assembly for a file
src/kiss_fftr.c.s:
	$(MAKE) -f CMakeFiles/mic_array.dir/build.make CMakeFiles/mic_array.dir/src/kiss_fftr.c.s
.PHONY : src/kiss_fftr.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/mic_array.dir/build.make CMakeFiles/mic_array.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/mic_array.dir/build.make CMakeFiles/mic_array.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/mic_array.dir/build.make CMakeFiles/mic_array.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... mic_array"
	@echo "... src/hq_malloc.o"
	@echo "... src/hq_malloc.i"
	@echo "... src/hq_malloc.s"
	@echo "... src/hq_tx_2mic_ns.o"
	@echo "... src/hq_tx_2mic_ns.i"
	@echo "... src/hq_tx_2mic_ns.s"
	@echo "... src/kiss_fft.o"
	@echo "... src/kiss_fft.i"
	@echo "... src/kiss_fft.s"
	@echo "... src/kiss_fftr.o"
	@echo "... src/kiss_fftr.i"
	@echo "... src/kiss_fftr.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

